### ISSUE TITLE
Dúvida sobre as funcionalidades

### ISSUE THREAD

**Issue by fnoquiq** [flaviogf/cmc7#1]
Curti muito o projeto, gostaria de saber se é possível verificar se o CMC-7 é válido, antes de retirar os dados como 'cmc7-agencia' ou 'cmc7.banco'.

Não encontrei a informação no README.md

**Comment by flaviogf** [comment]
Da hora ... Atualmente não. Ela está verificando somente o length da string, que é passada no construtor, e lançando uma exceção caso seja diferente de 30.

**Comment by fnoquiq** [comment]
Da uma olhada nesse repo: https://github.com/iCheques/cmc7-validador

Este faz somente validações, porém mais pesadas.

```js
const CMC7Validator = require('cmc7-validator');
new CMC7Validator('450445043466147665081657326823').isValid(); // returns true
new CMC7Validator('45044504 34661476650816 57326823').isValid(); // returns true
new CMC7Validator('Oi! Oi! Oi!').isValid(); // returns false
```

O que acha de integrar aquelas funcionalidades a este repositório, assim fazemos uma lib mais completa, juntando os melhores dos dois.

**Comment by fnoquiq** [comment]
Vou tentar subir uma pull request

**Comment by fnoquiq** [comment]
Olhando o código deles, eles fazem a validação usando o dígito verificador.

```js
const dv1 = checkdigit.mod10.create(this.group1);
const dv2 = checkdigit.mod10.create(this.group2);
const dv3 = checkdigit.mod10.create(this.group3);

return this.dv1 === dv1 && this.dv2 === dv2 && this.dv3 === dv3;
```

Além disso eles já tratam a sequência de números com expressões regulares. 

Você conseguiria incluir estas verificações ao seu projeto? Estou querendo usar está lib em produção futuramente para um projeto.

Obs: Tentei subir um pull request integrando essas validações mas falhei :(
